blank_issues_enabled: false
contact_links:
  - name: Questions & Support
    url: https://github.com/yuichiroyamaji/bms/discussions
    about: For questions and support other than bug reports or feature requests, please use Discussions.